### ISSUE TITLE
checking the column

### ISSUE THREAD

**Issue by IanaKhitsko** [masha2808/game-lab1#1]
https://github.com/masha2808/game-lab1/blob/0a82f639fddc6888a0dab2375480ff883fd7cc80/src/game.js#L49

I don't get it. What is the sense of checking the last element in sequence first and then step by step? Can we just call here
 return j - CONSTANTS.STEP >= 0 && 
    i + CONSTANTS.STEP < CONSTANTS.MATRIX_SIZE && 
    checkWinner(checkLeftDiagonalByStep, data, i, j, CONSTANTS.STEP);

?
The same question for other directions

**Comment by masha2808** [comment]
Program will work correctly if checkLeftDiagonalByStep function is not used and checkWinner function gets CONSTANTS.STEP instead of CONSTANTS.STEP - 1. However checking first and fifth elements with checkLeftDiagonalByStep(data, i, j, CONSTANTS.STEP) allows to avoid unnecessary comparison of matrix elements, because if first and fifth elements are different, it is doesn't matter which values have second, third and fourth elements. So, if checkLeftDiagonalByStep in line 49 returns false, checkWinner function is not called and second, third and fourth elements are not checked. The same logic applies to other functions
